export const RESIGNATION_STATUS = {
  SUBMITTTED: 'SUBMITTTED',
  VOLUNTARY_WITHDRAWAL: 'VOLUNTARY_WITHDRAWAL',
  APPROVED_BY_RM: 'APPROVED_BY_RM',
  APPROVED_BY_HR: 'APPROVED_BY_HR',
  SCHEDULED_MEETING: 'SCHEDULED_MEETING',
  REVERSE_TERMINATION: 'REVERSE_TERMINATION'
};
